In [2]:
import pandas as pd

samsung_price = pd.read_csv('../Data/삼성전자 종가.csv', index_col = 0, header = 0)
samsung_price = samsung_price.squeeze()

samsung_price.index[samsung_price.max() == samsung_price.values][0]

'2021-01-11'

In [3]:
import numpy as np

In [8]:
ls = [1,2,3,4]
ls
ls[0]

1

In [11]:
arr = np.array([1,2,3,4])
arr
arr[0]

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2
arr2.shape


(2, 4)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr[1]

2

In [40]:
arr3 = np.array([[1,2], [2,5]])

arr3 + 1

array([[2, 3],
       [3, 6]])

In [41]:
arr3 * 10

array([[10, 20],
       [20, 50]])

In [43]:
samsung_price*100

Date
2018-01-02    5102000
2018-01-03    5162000
2018-01-04    5108000
2018-01-05    5212000
2018-01-08    5202000
               ...   
2021-12-13    7680000
2021-12-14    7700000
2021-12-15    7760000
2021-12-16    7780000
2021-12-17    7800000
Name: Close, Length: 977, dtype: int64